# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "open-ost.ch"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    resources:
    - compress: false
      names:
      - client
      - federation
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['0.0.0.0']
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
# database:
#   name: psycopg2
#   args:
#     user: openost
#     password: '{{ lookup('passwordstore', 'deploy/synapse-db-pass directory=pass/') }}'
#     database: synapse
#     host: synapse-db
#     cp_min: 5
#     cp_max: 10
log_config: "/data/matrix.open-ost.ch.log.config"
media_store_path: /data/media_store
registration_shared_secret: >- 
  {{ lookup('passwordstore', 'deploy/synapse-registration-secret directory=pass/') }}
report_stats: false
macaroon_secret_key: >- 
  {{ lookup('passwordstore', 'deploy/synapse-macaroon-secret directory=pass/') }}
form_secret: >- 
  {{ lookup('passwordstore', 'deploy/synapse-form-secret directory=pass/') }}
signing_key_path: "/data/matrix.open-ost.ch.signing.key"
matrix_synapse_allow_public_rooms_over_federation: true
encryption_enabled_by_default_for_room_type: all
# done by traefik 
# serve_server_wellknown: true
public_baseurl: "https://matrix.open-ost.ch/"
enable_cors: true
enable_registration: true
registration_requires_token: true
federation_enabled: true
trusted_key_servers:
  - server_name: "matrix.org"
federation_domain_whitelist:
  - "matrix.org"
  - "chab.is"
  - "studentchat.ethz.ch"
send_presence_to_federation: false
federation_verify_certificates: true

# vim:ft=yaml
