services:
  traefik:
    image: traefik:v3.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/letsencrypt:/letsencrypt
    labels:
      # TODO: remove
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.open-ost.ch`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      # - "traefik.http.routers.dashboard.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$..."
    networks:
      proxy:
    depends_on:
      - openost
      - gamejam

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 300

  openost:
    image: openhsr/openost:latest
    restart: unless-stopped
    networks:
      openost:
      proxy:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.openost-www.rule=Host(`www.open-ost.ch`)"
      - "traefik.http.routers.openost-www.entrypoints=websecure"
      - "traefik.http.routers.openost-www.service=openost"
      - "traefik.http.routers.openost-www.tls=true"
      - "traefik.http.routers.openost-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openost-www.tls.domains[0].main=open-ost.ch"
      - "traefik.http.routers.openost-www.tls.domains[0].sans=www.open-ost.ch"

      - "traefik.http.routers.openost-redirect.rule=Host(`open-ost.ch`)"
      - "traefik.http.routers.openost-redirect.entrypoints=websecure"
      - "traefik.http.routers.openost-redirect.service=openost"
      - "traefik.http.routers.openost-redirect.tls=true"
      - "traefik.http.routers.openost-redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openost-redirect.middlewares=redirect-to-www"

      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https://open-ost\\.ch/(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.open-ost.ch/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"

      - "traefik.http.services.openost.loadbalancer.server.port=6000"

  gamejam:
    image: openhsr/gamejam:latest
    restart: unless-stopped
    networks:
      gamejam:
      proxy:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.gamejam.rule=Host(`game-jam.open-ost.ch`)"
      - "traefik.http.routers.gamejam.entrypoints=websecure"
      - "traefik.http.routers.gamejam.service=gamejam"
      - "traefik.http.routers.gamejam.tls=true"
      - "traefik.http.routers.gamejam.tls.certresolver=letsencrypt"
      - "traefik.http.services.gamejam.loadbalancer.server.port=6001"

  # synapse:
  #   container_name: synapse
  #   image: docker.io/matrixdotorg/synapse:latest
  #   restart: unless-stopped
  #   environment:
  #     - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
  #     - UID=1000
  #     - GID=1000
  #   volumes:
  #     - ./data/synapse:/data
  #     - ./config/synapse/homeserver.yaml:/data/homeserver.yaml:ro
  #     - ./config/synapse/matrix.open-ost.ch.log.config:/data/matrix.open-ost.ch.log.config:ro
  #   depends_on:
  #     - synapse-db
  #   networks:
  #     synapse:
  #     proxy:
  #       ipv4_address: 192.168.10.70
  #
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=proxy"
  #
  # synapse-db:
  #   image: docker.io/postgres:15-alpine
  #   container_name: synapse-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=synapse_user
  #     - POSTGRES_PASSWORD=secure_password
  #     - POSTGRES_DB=synapse
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   volumes:
  #     - ./data/synapse-db:/var/lib/postgresql/data
  #   networks:
  #     synapse:

networks:
  synapse:
  gamejam:
  openost:
  proxy:
    name: proxy
    driver: bridge

volumes:
  letsencrypt:
