services:
  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true" # TODO: remove
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      proxy:
    restart: unless-stopped
    depends_on:
      - openost
      - gamejam

  watchtower:
    image: nickfedor/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 300

  openost:
    image: openhsr/openost:latest
    ports:
      - "3000:3443"
    networks:
      openost:
      proxy:
        ipv4_address: 192.168.10.72
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.openost.rule=Host(`openost.localhost`)"

      # HTTP to HTTPS Redirect
      - "traefik.http.routers.openost.entrypoints=http"
      - "traefik.http.routers.openost.rule=Host(`open-ost.ch`)"
      - "traefik.http.middlewares.openost-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.openost.middlewares=openost-https-redirect"

      # Main Secure Router for openost
      - "traefik.http.routers.openost-https.entrypoints=https"
      - "traefik.http.routers.openost-https.rule=Host(`open-ost.ch`) || Host(`www.open-ost.ch`)"
      - "traefik.http.routers.openost-https.service=openost"
      - "traefik.http.routers.openost-https.tls=true"
      - "traefik.http.routers.openost-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openost-https.tls.options=modern-tls"
      - "traefik.http.routers.openost-https.tls.domains[0].main=open-ost.com"
      - "traefik.http.routers.openost-https.tls.domains[0].sans=www.open-ost.com"

  gamejam:
    image: openhsr/gamejam:latest
    ports:
      - "4000:4443"
    networks:
      gamejam:
      proxy:
        ipv4_address: 192.168.10.71
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.http.routers.gamejam.rule=Host(`gamejam.localhost`)"

  # synapse:
  #   container_name: synapse
  #   image: docker.io/matrixdotorg/synapse:latest
  #   restart: unless-stopped
  #   environment:
  #     - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
  #     - UID=1000
  #     - GID=1000
  #   volumes:
  #     - ./data/synapse:/data
  #     - ./config/synapse/homeserver.yaml:/data/homeserver.yaml
  #     - ./config/synapse/matrix.open-ost.ch.log.config:/data/matrix.open-ost.ch.log.config
  #     - ./config/synapse/homeserver.yaml:/data/homeserver.yaml
  #   depends_on:
  #     - synapse-db
  #   networks:
  #     synapse:
  #     proxy:
  #       ipv4_address: 192.168.10.70
  #
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=proxy"
  #
  # synapse-db:
  #   image: docker.io/postgres:15-alpine
  #   container_name: synapse-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=synapse_user
  #     - POSTGRES_PASSWORD=secure_password
  #     - POSTGRES_DB=synapse
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   volumes:
  #     - ./data/synapse-db:/var/lib/postgresql/data
  #   networks:
  #     synapse:

networks:
  synapse:
  gamejam:
  openost:
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
