services:
  # cursedness
  backup-sp:
    image: restic/rest-server:latest
    restart: unless-stopped
    environment:
      OPTIONS: "--append-only --private-repos"
      PASSWORD_FILE: "/data/.htpasswd"
    mem_limit: 512m
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ../data/backup-sp:/data
    networks:
      backup-sp:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=backup-sp"

      - "traefik.http.routers.backup-sp.rule=Host(`backup.open-ost.ch`)"
      - "traefik.http.routers.backup-sp.entrypoints=websecure"
      - "traefik.http.routers.backup-sp.service=backup-sp"
      - "traefik.http.routers.backup-sp.tls=true"
      - "traefik.http.routers.backup-sp.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backup-sp.tls.domains[0].main=backup.open-ost.ch"
      - "traefik.http.services.backup-sp.loadbalancer.server.port=8000"

      # - "traefik.http.routers.backup-sp.middlewares=crowdsec@docker,backup-sp-ratelimit@docker"
      # - "traefik.http.middlewares.backup-sp-ratelimit.ratelimit.average=100"
      # - "traefik.http.middlewares.backup-sp-ratelimit.ratelimit.period=1m"
      # - "traefik.http.middlewares.backup-sp-ratelimit.ratelimit.burst=50"
  vikunja:
    image: vikunja/vikunja:2.6.0
    mem_limit: 512m
    cpus: "1.0"
    env_file: ~/vikunja.env
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.open-ost.ch/
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_MAILER_ENABLED: "true"
      VIKUNJA_MAILER_HOST: "asmtp.mail.hostpoint.ch"
      VIKUNJA_MAILER_PORT: "465"
      VIKUNJA_MAILER_USERNAME: "info@open-ost.ch"
      VIKUNJA_MAILER_FROMEMAIL: "admin@open-ost.ch"
    networks:
      vikunja:
    # TODO: ansible chown 1000 files db
    volumes:
      - ../data/vikunja/files:/app/vikunja/files
      - ../data/vikunja/db:/db
      - ../config/vikunja/config.yml:/etc/vikunja/config.yml
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=vikunja"

      - "traefik.http.routers.vikunja.rule=Host(`vikunja.open-ost.ch`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.service=vikunja"
      - "traefik.http.routers.vikunja.tls=true"
      - "traefik.http.routers.vikunja.tls.certresolver=letsencrypt"
      - "traefik.http.routers.vikunja.tls.domains[0].main=vikunja.open-ost.ch"
      - "traefik.http.services.vikunja.loadbalancer.server.port=3456"

networks:
  backup-sp:
    name: backup-sp
  vikunja:
    name: vikunja
