services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.8
    restart: unless-stopped
    environment:
        # crowdsecurity/http-cve
        # crowdsecurity/http-dos
      COLLECTIONS: >-
        crowdsecurity/traefik
      BOUNCER_KEY_traefik: ${CROWDSEC_BOUNCER_KEY}

    volumes:
      - ./data/traefik:/var/log/traefik:ro
      - ./config/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./data/crowdsec/config:/etc/crowdsec
      - ./data/crowdsec/data:/var/lib/crowdsec/data

    networks:
      proxy:

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 900

  authentik-db:
    networks:
      authentik:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ~/authentik.env
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    volumes:
      - ./data/authentik-db:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  authentik-server:
    networks:
      authentik:
    command: server
    depends_on:
      authentik-db:
        condition: service_healthy
    env_file:
      - ~/authentik.env
    image: authentik/server:2026.8
    restart: unless-stopped
    shm_size: 512mb
    volumes:
      - ./data/authentik/data:/data
      - ./data/authentik/custom-templates:/templates
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=authentik"

      - "traefik.http.routers.authentik.rule=Host(`authentik.open-ost.ch`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.service=authentik"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authentik.tls.domains[0].main=authentik.open-ost.ch"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"

  authentik-worker:
    networks:
      authentik:
    command: worker
    depends_on:
      authentik-db:
        condition: service_healthy
    env_file:
      - ~/authentik.env
    image: authentik/server:2026.8
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/authentik/data:/data
      - ./data/authentik/certs:/certs
      - ./data/authentik/custom-templates:/templates
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  database:
    driver: local

networks:
  authentik:
