services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.8
    restart: unless-stopped
    environment:
        # crowdsecurity/http-cve
        # crowdsecurity/http-dos
      COLLECTIONS: >-
        crowdsecurity/traefik
      BOUNCER_KEY_traefik: ${CROWDSEC_BOUNCER_KEY}

    volumes:
      - ../data/traefik:/var/log/traefik:ro
      - ../config/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ../data/crowdsec/config:/etc/crowdsec
      - ../data/crowdsec/data:/var/lib/crowdsec/data

    networks:
      proxy:

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 900
