services:
  traefik:
    image: traefik:v3.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/letsencrypt:/letsencrypt
    networks:
      proxy:
      openost:
      gamjam:
      synapse:
      backup-sp:
    depends_on:
      - openost
      - gamejam

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/.docker/config.json:/config.json
    command: --interval 900

  openost:
    image: openhsr/openost:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    networks:
      openost:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=openost"

      - "traefik.http.routers.openost-www.rule=Host(`www.open-ost.ch`)"
      - "traefik.http.routers.openost-www.entrypoints=websecure"
      - "traefik.http.routers.openost-www.service=openost"
      - "traefik.http.routers.openost-www.tls=true"
      - "traefik.http.routers.openost-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openost-www.tls.domains[0].main=open-ost.ch"
      - "traefik.http.routers.openost-www.tls.domains[0].sans=www.open-ost.ch"

      - "traefik.http.routers.openost-redirect.rule=Host(`open-ost.ch`)"
      - "traefik.http.routers.openost-redirect.entrypoints=websecure"
      - "traefik.http.routers.openost-redirect.service=openost"
      - "traefik.http.routers.openost-redirect.tls=true"
      - "traefik.http.routers.openost-redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openost-redirect.middlewares=redirect-to-www"

      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https://open-ost\\.ch/(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.open-ost.ch/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"

      - "traefik.http.services.openost.loadbalancer.server.port=3000"

  gamejam:
    image: openhsr/gamejam:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    networks:
      gamejam:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=gamejam"

      - "traefik.http.routers.gamejam.rule=Host(`game-jam.open-ost.ch`)"
      - "traefik.http.routers.gamejam.entrypoints=websecure"
      - "traefik.http.routers.gamejam.service=gamejam"
      - "traefik.http.routers.gamejam.tls=true"
      - "traefik.http.routers.gamejam.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gamejam.tls.domains[0].main=game-jam.open-ost.ch"
      - "traefik.http.services.gamejam.loadbalancer.server.port=3000"

  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./config/element/config.json:/app/config.json:ro
    networks:
      synapse:
    depends_on:
      - synapse

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=synapse"

      - "traefik.http.routers.element.rule=Host(`element.open-ost.ch`)"
      - "traefik.http.routers.element.entrypoints=websecure"
      - "traefik.http.routers.element.service=element"
      - "traefik.http.routers.element.tls=true"
      - "traefik.http.routers.element.tls.certresolver=letsencrypt"
      - "traefik.http.routers.element.tls.domains[0].main=element.open-ost.ch"
      - "traefik.http.services.element.loadbalancer.server.port=8008"

  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    env_file: ~/open-ost.env
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./data/synapse:/data
      - ./config/synapse/homeserver.yaml:/data/homeserver.yaml:ro
      - ./config/synapse/matrix.open-ost.ch.log.config:/data/matrix.open-ost.ch.log.config:ro
    # depends_on:
    #   - synapse-db
    networks:
      synapse:

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=synapse"

      - "traefik.http.routers.synapse.rule=Host(`matrix.open-ost.ch`)"
      - "traefik.http.routers.synapse.entrypoints=websecure"
      - "traefik.http.routers.synapse.service=synapse"
      - "traefik.http.routers.synapse.tls=true"
      - "traefik.http.routers.synapse.tls.certresolver=letsencrypt"
      - "traefik.http.routers.synapse.tls.domains[0].main=matrix.open-ost.ch"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"

      - "traefik.http.routers.synapse-wellknown.rule=Host(`open-ost.ch`) && PathPrefix(`/.well-known/matrix/`)"
      - "traefik.http.routers.synapse-wellknown.entrypoints=websecure"
      - "traefik.http.routers.synapse-wellknown.service=synapse"
      - "traefik.http.routers.synapse-wellknown.tls=true"
      - "traefik.http.routers.synapse-wellknown.tls.certresolver=letsencrypt"

  # TODO:
  # synapse-db:
  #   image: docker.io/postgres:15-alpine
  #   env_file: ~/open-ost.env
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/synapse-db:/var/lib/postgresql/data
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   networks:
  #     synapse:

  # cursedness
  backup-sp:
    image: restic/rest-server:latest
    restart: unless-stopped
    environment:
      OPTIONS: "--append-only --private-repos"
      PASSWORD_FILE: "/data/.htpasswd"
    mem_limit: 512m
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./data/backup-sp:/data
    networks:
      backup-sp:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=backup-sp"

      - "traefik.enable=true"
      - "traefik.http.routers.backup-sp.rule=Host(`backup.open-ost.ch`)"
      - "traefik.http.routers.backup-sp.entrypoints=websecure"
      - "traefik.http.routers.backup-sp.service=backup-sp"
      - "traefik.http.routers.backup-sp.tls=true"
      - "traefik.http.routers.backup-sp.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backup-sp.tls.domains[0].main=backup.open-ost.ch"
      - "traefik.http.services.backup-sp.loadbalancer.server.port=8000"
networks:
  synapse:
    name: synapse
  gamejam:
    name: gamejam
  openost:
    name: openost
  backup-sp:
    name: backup-sp
  proxy:
    name: proxy
