include:
  - docker/web.yaml 
  - docker/matrix.yaml 
  - docker/misc.yaml 
  - docker/monitoring.yaml 
  - docker/secoority.yaml 
services:
  traefik:
    image: traefik:v3.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/letsencrypt:/letsencrypt
      - ./data/traefik:/var/log/traefik
    networks:
      proxy:
      openost:
      gamejam:
      synapse:
      backup-sp:
      vikunja:
      authentik:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${CROWDSEC_BOUNCER_KEY}"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapischeme=http"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapihost=crowdsec:8080"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode=stream"

networks:
  proxy:
    name: proxy
