entryPoints:
  web:
    address: ":80"
    http:
      aliasHeadersStrategy: delete
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      encodedCharacters:
        allowEncodedSlash: true # matrix
        allowEncodedHash: true # matrix
        allowEncodedBackSlash: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
  websecure:
    address: ":443"
    http:
      aliasHeadersStrategy: delete
      encodedCharacters:
        allowEncodedSlash: true # matrix
        allowEncodedHash: true # matrix
        allowEncodedBackSlash: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@open-ost.ch
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: false
  insecure: false

log:
  level: INFO

accesslog: 
  filepath: /var/log/traefik/access.log
  format: json

experimental:
  plugins:
    bouncer:
      modulename: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.7.1
    inlineResponse:
      moduleName: github.com/tuxgal/traefik_inline_response
      version: v0.1.2
