entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      aliasHeadersStrategy: delete
      encodedCharacters:
        # TODO: shouldn't cause any problems? i think?
        allowEncodedSlash: false
        allowEncodedBackSlash: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
        allowEncodedHash: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@open-ost.ch
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: false
  insecure: false

log:
  level: INFO

accesslog: true
