---
- name: Clone infra repository
  ansible.builtin.git:
    repo: https://github.com/openost/infra/
    dest: /home/open-ost/infra

- name: Install open-ost environment file
  ansible.builtin.template:
    src: open-ost.env
    dest: /home/open-ost/open-ost.env
    owner: open-ost
    group: open-ost
    mode: "0600"

- name: Install docker environment file
  ansible.builtin.template:
    src: docker.env
    dest: /home/open-ost/infra/docker/.env
    owner: open-ost
    group: open-ost
    mode: "0600"

- name: Create data directories
  become: true
  ansible.builtin.file:
    path: "/home/open-ost/infra/docker/data/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
  loop:
    - name: synapse-db
      owner: 999 # postgres uid
    - name: letsencrypt
      owner: open-ost
    - name: synapse/media_store
      owner: 991

- name: Install synapse homeserver.yaml
  become: true
  ansible.builtin.template:
    src: homeserver.yaml
    dest: /home/open-ost/infra/docker/config/synapse/
    owner: 991
    group: 991
    mode: "0600"

- name: Install synapse signing key
  become: true
  ansible.builtin.copy:
    content: "{{ lookup('community.general.passwordstore', 'deploy/synapse-signing-key', directory='pass/') }}"
    dest: /home/open-ost/infra/docker/data/synapse/matrix.open-ost.ch.signing.key
    owner: 991
    group: 991
    mode: "0600"

- name: Create acme.json
  ansible.builtin.file:
    path: /home/open-ost/infra/docker/data/letsencrypt/acme.json
    state: touch
    owner: open-ost
    mode: '600'
    modification_time: preserve
    access_time: preserve

- name: Set up open-ost docker containers
  community.docker.docker_compose_v2:
    project_src: ~/infra/docker
    files: docker-compose.yaml


# TODO: sudo chown -R 991:991 data/synapse
# TODO: sudo chown -R 999:999 data/synapse-db
